[package]
name = "euterpe-preprocessor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
hound = "3.5.1"
rayon = "1.8.0"
walkdir = "2.4.0"
